{{ if .Values.configs }}
{{ if gt (len .Values.configs) 0 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transfer-hub-api.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "transfer-hub-api.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configs }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{ end }}
{{ end }}