{{ if .Values.secrets }}
{{ if gt (len .Values.secrets) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transfer-hub-api.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "transfer-hub-api.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{ end }}
{{ end }}